file_format: "1"
id: chocorne
name: chocorne
type: shield
url: https://github.com/ddelriomonferrer/zmk-config
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - chocorne_left
  - chocorne_right
